language: ruby
rvm: 2.1
env:
  global:
  - secure: Kc5j0fwV/6zHeENXidold1kRCHN7BKVY88Oe+0nNaqlJeaHfm+TUDTrhNghtYk2cEf1hM3SqgUozJvqGGWv+VkmMewv3UBWn0q21qLpyn8NgscnYAATrR4mEZMzq0ZWA63l/6t2l8v8wK7Y15PnbK990u5BLpLyTSqubfLXcx8k=
  - secure: UVZQf9xGW3CDvUSpnraw7/MWGiYLFaMPoPNNBuHwrugsWihu0abFbUpRICLA3+iYO6bl1ngwy8WAtL7auAPCm9lR4zGYuIB0cTaJtQ95hHCTHK/9ix6LVcVxfvKwzWWY3Sg3s3xRQfNzrtbufzNowkooQrnHtgrlYbs4RM9lnTA=
install:
- npm install
before_script:
- npm test
script:
- scripts/build.sh
before_deploy:
- echo "@pact-foundation:registry=https://registry.npmjs.org/" > .npmrc
- echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" >> .npmrc
- echo "//registry.npmjs.org/:username=pact-foundation" >> .npmrc
- echo "//registry.npmjs.org/:email=pact-foundation@googlegroups.com" >> .npmrc
- echo "//registry.npmjs.org/:always-auth=true" >> .npmrc
- cp .npmrc build/pact-provider-verifier-darwin/
- cp .npmrc build/pact-provider-verifier-win32/
- cp .npmrc build/pact-provider-verifier-linux-ia32/
- cp .npmrc build/pact-provider-verifier-linux-x64/
deploy:
- provider: script
  skip_cleanup: true
  script: cd build/pact-provider-verifier-darwin/ && npm publish . --access public
- provider: script
  skip_cleanup: true
  script: cd build/pact-provider-verifier-linux-ia32/ && npm publish . --access public
- provider: script
  skip_cleanup: true
  script: cd build/pact-provider-verifier-linux-x64/ && npm publish . --access public
- provider: script
  skip_cleanup: true
  script: cd build/pact-provider-verifier-win32/ && npm publish . --access public
after_failure:
- find . -iname '*.log' -print0 | xargs -0 cat
